### ISSUE TITLE
Ignore chrX for normalization

### ISSUE THREAD

**Issue by vivekbhr** [maxplanck-ie/snakemake_workflows#36]
X chromsome should be excluded for calculation of 1x normalization in bamCoverage..

**Comment by steffenheyne** [comment]
you mean with the option `–ignoreForNormalization` ? this only effects normalization factors, but not the bigWig, right? ie. we also get coverage on the ignored chromosomes!?

**Comment by vivekbhr** [comment]
yes It just excludes the given chromosome for calculation of norm factors..

We should ignore both X and M..

**Comment by steffenheyne** [comment]
yes, this should make tracks better comparable and less prune to sample specific biases, 
could be very important for some chip-seq samples...
Maybe also exclude Y to be really independent of sex specific biases and to allow for better male/female comparisons!?

We need to adjust the effective genome size, or!?

**Comment by vivekbhr** [comment]
Yes I think we should also remove Y.. 

effective genome size : I don't think so but I would confirm once more with fidel and devon tomorrow..

**Comment by steffenheyne** [comment]
there is no --perchr right now, but could be nice to have...

at least this would allow to compare also tracks coming from slight different reference genomes (some use random/unplaced contigs, some only chr 1-19/21 etc.), within one workflow run this is not a problem as all samples mapped to the same reference and hence same number of chromosomes...

for small chr a --perchr normalization might introduced again unwanted biases, so one might use something like an "autosomal"/major chr normalization, ie. only use chr that contribute eg. >5% of total genome size...

**Comment by steffenheyne** [comment]
does "--ignoreForNormalization Y X M" fail if eg. a genome/bam index does not contain a listed chromosome? "M" is eg. not part of dm6, there M is called "dmel_mitochondrion_genome"...

This could become actually complicated for different organisms. 
Better could be to define the ignore list in the organism config yaml (eg shared/organisms/dm6.yaml). 

Furthermore, if we going this "better normalization" route, we might also exclude all other scaffolds for normalization etc because some of them are also on X and Y. Maybe it is now easier to define a "white list" of chr names that *should* be used for normalization? (and in snakemake/internals we convert this to a "black list" according to the used genome index that is used in deeptools rules?)

**Comment by steffenheyne** [comment]
implemented in develop now
